MediaMarket/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from products.views import about_us, homepage

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", homepage, name="homepage"),
    path("about-us/", about_us, name="about_us"),
    path("users/", include("users.urls", namespace="users")),
    path("products/", include("products.urls", namespace="products")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from .views import (
    products_list,
    product_detail,
    category_sort,
    category_filter,
    product_cart,
    add_product_to_cart,
    remove_product_from_cart,
    favorite_product,
    add_product_to_favorite,
    remove_product_to_favorite,
    product_checkout,
    users_order,
    order_repeat,
)

app_name = "products"

urlpatterns = [
    path("catalog/", products_list, name="products_list"),
    path("product_detail/<pk>", product_detail, name="product_detail"),
    path("category/sort/", category_sort, name="category_sort"),
    path("category/filter/", category_filter, name="category_filter"),
    path("cart/", product_cart, name="product_cart"),
    path("cart/add/<pk>", add_product_to_cart, name="add_product_to_cart"),
    path("cart/remove/<pk>", remove_product_from_cart, name="remove_product_from_cart"),
    path("favorite/", favorite_product, name="favorite_product"),
    path("favorite/add/<pk>", add_product_to_favorite, name="add_product_to_favorite"),
    path(
        "favorite/remove/<pk>",
        remove_product_to_favorite,
        name="remove_product_to_favorite",
    ),
    path("checkout/", product_checkout, name="product_checkout"),
    path("users_order/", users_order, name="users_order"),
    path("order-repeat/<int:pk>/", order_repeat, name="order_repeat"),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (
    UserLoginView,
    UserRegisterView,
    UserRecoverPasswordView,
    user_profile,
    UserProfileSettingsView,
    user_profile_orders,
)

app_name = "users"

urlpatterns = [
    path("profile/<pk>", user_profile, name="user_profile"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path(
        "recover-password/", UserRecoverPasswordView.as_view(), name="recover-password"
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("settings/", UserProfileSettingsView.as_view(), name="user_profile_settings"),
    path("orders/<pk>", user_profile_orders, name="user_profile_orders"),
]

products/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ("full_name", "address", "phone", "email")
        widgets = {
            "full_name": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Иванов Иван Иванович"
            }),
            "address": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "ул. Пушкина, д. 1, кв. 1"

            }),
            "phone": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "+7XXXXXXXXXX или 8XXXXXXXXXX"
            }),
            "email": forms.EmailInput(attrs={
                "class": "form-control",
                "placeholder": "example@email.com"
            }),
        }

products/views.py
from django.contrib.auth.decorators import login_required
from django.db import connection
from django.shortcuts import get_object_or_404, redirect, render

from MediaMarket.settings import LOGIN_URL

from .forms import OrderForm
from .models import Cart, Favorite, Order, Product, ProductInCart, ProductInOrder



def homepage(request):
    return render(request, "homepage.html", {"title": "Главная страница"})


def about_us(request):
    return render(request, "about_us.html", {"title": "О нас"})


def products_list(request):
    query = request.GET.get("q", "")
    products = Product.objects.all()
    if query:
        query_lower = query.lower()
        products = [
            product
            for product in products
            if query_lower in product.name.lower()
            or query_lower in product.description.lower()
        ]
    response = render(
        request, "products/products_list.html", {"products": products, "query": query}
    )
    print(f"products_list executed {len(connection.queries)} SQL queries")
    return response


def product_detail(request, pk):
    product = Product.objects.get(pk=pk)
    if request.method == "POST":
        quantity = request.POST.get("quantity")
        cart, created = Cart.objects.get_or_create(user=request.user)
        product_in_cart, created = ProductInCart.objects.get_or_create(
            cart=cart, product=product
        )
        if created:
            product_in_cart.quantity = quantity
        else:
            product_in_cart.quantity += int(quantity)
        product_in_cart.save()
    return render(request, "products/product_detail.html", {"product": product})


def category_sort(request):
    products = Product.objects.all()

    sort_param = request.GET.get("sort")
    if sort_param == "price_asc":
        products = products.order_by("price")
    elif sort_param == "price_desc":
        products = products.order_by("-price")
    elif sort_param == "date":
        products = products.order_by("-created_at")

    return render(request, "products/products_list.html", {"products": products})


def category_filter(request):
    products = Product.objects.all()
    filter_param = request.GET.get("filter")
    current_category = None
    if filter_param in ["electronic", "household_goods", "animal", "podarok"]:
        products = products.filter(category__slug=filter_param)
        current_category = filter_param

    # if filter_param == 'electronic':
    #     products = products.filter(category__slug='electronic')
    #     current_category = 'electronic'
    # elif filter_param == 'household_goods':
    #     products = products.filter(category__slug='household_goods')
    #     current_category = 'household_goods'
    # elif filter_param == 'animal':
    #     products = products.filter(category__slug='animal')
    #     current_category = 'animal'
    # elif filter_param == 'podarok':
    #     products = products.filter(category__slug='podarok')
    #     current_category = 'podarok'

    return render(
        request,
        "products/products_list.html",
        {"products": products, "current_category": current_category},
    )


def product_cart(request):
    if request.user.is_authenticated:
        cart = Cart.objects.get(user=request.user)
        cart_items = ProductInCart.objects.filter(cart=cart)
        total_price = cart.total_price()

    else:
        cart_item = request.session.get("cart", {})
        cart_items = Product.objects.filter(pk__in=cart_item.keys())
        total_price = 0
        for product in cart_items:
            product.total_price = product.price * cart_item[str(product.pk)]
            total_price += product.total_price

    recomended_products = Product.objects.order_by("?")[:4]
    return render(
        request,
        "products/product_cart.html",
        {
            "title": "Моя корзина",
            "cart_items": cart_items,
            "total_price": total_price,
            "recommended_products": recomended_products,
        },
    )


def add_product_to_cart(request, pk):
    if request.user.is_authenticated:
        product = Product.objects.get(pk=pk)
        cart, created = Cart.objects.get_or_create(user=request.user)

        product_in_cart, created = ProductInCart.objects.get_or_create(
            cart=cart, product=product
        )

        if not created:
            product_in_cart.quantity += 1
            product_in_cart.save()

    else:
        cart = request.session.get("cart", {})
        cart[pk] = cart.get(pk, 0) + 1
        request.session["cart"] = cart

    return redirect("products:product_cart")


def remove_product_from_cart(request, pk):
    if request.user.is_authenticated:
        product = Product.objects.get(pk=pk)
        cart = Cart.objects.get(user=request.user)
        cart.products.remove(product)

    else:
        cart = request.session.get("cart", {})
        if pk in cart:
            del cart[pk]
            request.session["cart"] = cart

    return redirect("products:product_cart")


@login_required(login_url=LOGIN_URL)
def favorite_product(request):
    if request.user.is_authenticated:
        favorite_items = Favorite.objects.filter(user=request.user)

    else:
        favorite_item = request.session.get("favorite", {})
        favorite_items = Product.objects.filter(pk__in=favorite_item.keys())

    recomended_products = Product.objects.order_by("?")[:4]
    return render(
        request,
        "products/product_favorite.html",
        {
            "title": "Избранное",
            "favorite_items": favorite_items,
            "recommended_products": recomended_products,
        },
    )


@login_required(login_url=LOGIN_URL)
def add_product_to_favorite(request, pk):
    if request.user.is_authenticated:
        product = Product.objects.get(pk=pk)
        favorite_item, created = Favorite.objects.get_or_create(
            user=request.user, product=product
        )

        if not created:
            favorite_item.save()

    else:
        favorite = request.session.get("favorite", {})
        favorite[pk] = favorite.get(pk, 0) + 1
        request.session["favorite"] = favorite

    return redirect(request.META.get("HTTP_REFERER", "products:products_list"))


@login_required(login_url=LOGIN_URL)
def remove_product_to_favorite(request, pk):
    if request.user.is_authenticated:
        Favorite.objects.filter(user=request.user, product_id=pk).delete()

    else:
        favorite = request.session.get("favorite", {})
        if pk in favorite:
            del favorite[pk]
            request.session["favorite"] = favorite

    return redirect("products:favorite_product")


@login_required(login_url=LOGIN_URL)
def product_checkout(request):
    if not request.user.is_authenticated:
        return redirect(f"{LOGIN_URL}?next={request.path}")

    cart = Cart.objects.get(user=request.user)
    cart_items = ProductInCart.objects.filter(cart=cart)

    if not cart_items.exists():
        return redirect("products:product_cart")

    if request.method == "POST":
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.total_price = cart.total_price()
            order.save()

            for item in cart_items:
                ProductInOrder.objects.create(
                    order=order,
                    product=item.product,
                    quantity=item.quantity
                )

            cart.products.clear()
            return redirect("products:products_list")
    else:
        form = OrderForm(initial={
            "full_name": request.user.get_full_name(),
            "email": request.user.email,
            "address": request.user.address_default,
        })

    total_price = 0
    for item in cart_items:
        item.total_price = item.product.price * item.quantity
        total_price += item.total_price

    shipping_price = {"direct": 500, "pickup": 1000}
    shipping_type = request.GET.get("shipping")
    sub_total_price = total_price

    if shipping_type in shipping_price:
        total_price += shipping_price[shipping_type]

    return render(request, "products/product_checkout.html", {
        "title": "Оформление заказа",
        "cart_items": cart_items,
        "total_price": total_price,
        "sub_total_price": sub_total_price,
        "shipping_price": shipping_price,
        "form": form,
    })


def users_order(request):
    if request.method == "POST":
        status = request.POST.get("status").split("_")
        order = Order.objects.get(pk=int(status[0]))
        order.status = status[1]
        order.save()

    orders = Order.objects.all().order_by("-created_at")

    status = orders[0]._meta.get_field("status").choices
    cart = Cart.objects.get(user=request.user)
    total_price = cart.total_price()

    return render(
        request,
        "products/users_order.html",
        {"orders": orders, "total_price": total_price, "status": status},
    )


def order_repeat(request, pk):
    order = get_object_or_404(Order, pk=pk, user=request.user)
    if request.method == "POST":
        new_order = Order.objects.create(user=request.user, status="new", total_price=0)
        for item in order.order_items.all():
            ProductInOrder.objects.create(
                order=new_order, product=item.product, quantity=item.quantity
            )
        new_order.total_price = sum(
            i.total_product_price() for i in new_order.order_items.all()
        )
        new_order.save()

        return redirect("products:order_repeat", pk=request.user.pk)

    return redirect("users:user_profile_orders", pk=request.user.pk)

templates/products/product_cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% with request.resolver_match.view_name as view_name %}
    <main class="main">
      <section class="section block-banner-cart mb-4" style="padding-top: 120px;">
        <div class="row">
          <div class="col-12">
            <div class="breadcrumbs">
              <ul class="list-inline">
                <li class="list-inline-item nav-link {% if view_name == 'homepage' %}active{% endif %}"> <a href="{% url 'homepage' %}">Главная </a></li>
                <li class="list-inline-item nav-link {% if view_name == 'products:products_list' %}active{% endif %}"> <a href="{% url 'products:products_list' %}">Каталог </a></li>
                <li class="list-inline-item nav-link {% if view_name == 'products:product_cart' %}active{% endif %}"> <a href="{% url 'products:product_cart' %}">Корзина </a></li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      <section class="section block-cart">
        <div class="row">
          <div class="col-lg-7">
            <div class="box-title-cart">
              <h4>Ваша корзина</h4>
              <h6>{% if cart_items %}{{ cart_items|length }} товар{{ cart_items|length|pluralize:"а,ов" }}{% else %}0 товаров{% endif %}</h6>
            </div>
            <div class="list-items-cart">
              {% if cart_items %}
                {% for item in cart_items %}
                <div class="item-cart">
                  <div class="item-cart-image">
                    {% if item.product.image %}
                    <img src="{{ item.product.image.url }}" alt="{{ item.product.name }}">
                    {% else %}
                    <img src="{{ item.image.url }}" alt="{{ item.name }}">
                    {% endif %}
                  </div>
                  <div class="item-cart-info">
                    <div class="item-cart-info-1">
                      <a class="text-16-medium" href="#">{{ item.product.name }}</a>
                      <div class="box-info-size-color-product">
                        <p class="box-color"><span class="body-p2 neutral-medium-dark">Цвет:</span><span class="body-p2 neutral-dark">{% if item.color %}{{ item.color }}{% else %}Стандартный{% endif %}</span></p>
                        <p class="box-size"><span class="body-p2 neutral-medium-dark">Размер:</span><span class="body-p2 neutral-dark">{% if item.size %}{{ item.size }}{% else %}Стандартный{% endif %}</span></p>
                      </div>
                      <div class="box-form-cart">
                        <div class="form-cart detail-qty"><span class="minus"></span>
                          <input class="qty-val form-control" type="text" name="quantity" value="{{ item.quantity }}" min="1"><span class="plus"></span>
                        </div>
                      </div>
                    </div>
                    <div class="item-cart-info-2">
                      <p class="body-p2">₽ {{ item.total_product_price }}</p>
                      <a class="btn-remove-cart" href="{% if request.user.is_authenticated %}{% url 'products:remove_product_from_cart' item.product.pk %}{% else %}{% url 'products:remove_product_from_cart' item.pk %}{% endif %}"></a>
                    </div>
                  </div>
                </div>
                {% endfor %}
              {% else %}
                <div class="alert alert-info">
                  <p>Ваша корзина пуста. <a href="{% url 'products:products_list' %}">Перейти в каталог</a></p>
                </div>
              {% endif %}
            </div>
            <div class="box-coupon">
              <div class="coupon-left">
                <input class="form-control input-coupon" type="text" placeholder="Промокод">
                <button class="btn btn-border">Применить</button>
              </div>
              <div class="coupon-right"><a class="btn btn-border" href="{% url 'products:products_list' %}">Продолжить покупки</a></div>
            </div>
            <div class="box-may-also-like">
              <h4 class="box-border-bottom mb-20">Вам также может понравиться</h4>
              <div class="list-items-also-like">
                {% for product in recommended_products %}
                <div class="item-also-like">
                  <div class="item-also-like-image">
                    {% if product.image %}
                    <img src="{{ product.image.url }}" alt="{{ product.name }}">
                    {% else %}
                    <img src="{% static 'assets/imgs/page/homepage1/product3.png' %}" alt="{{ product.name }}">
                    {% endif %}
                  </div>
                  <div class="item-also-like-info">
                    <div class="item-also-like-info-1">
                      <a class="text-16-medium" href="#">{{ product.name }}</a>
                      <p class="body-2 neutral-medium-dark mb-8">₽ {{ product.price }}</p>
                      <div class="box-color box-size mb-8"><span class="body-p2 neutral-medium-dark">Категория:</span>
                        <div class="dropdown">
                          <button class="btn dropdown-toggle" id="dropdownColor" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <span>{{ product.category.name }}</span>
                          </button>
                        </div>
                      </div>
                    </div>
                    <div class="item-also-like-info-2">
                      <div class="box-form-cart">
                        <div class="form-cart detail-qty"><span class="minus"></span>
                          <input class="qty-val form-control" type="text" name="quantity" value="1" min="1"><span class="plus"></span>
                        </div>
                        <a class="btn btn-black-medium" href="{% url "products:add_product_to_cart" product.pk %}">Добавить в корзину</a>
                        <a class="btn btn-red" href="{% url "products:add_product_to_favorite" product.pk %}">Добавить в избранное</a>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="col-lg-5">
            <div class="box-detail-cart">
              <h4 class="mb-25">Общая сумма:</h4>
              <div class="box-info-cart">
                <div class="d-flex align-items-center justify-content-between box-border-bottom">
{#                  <h5 class="neutral-medium-dark">Товары</h5>#}
                  <h5 class="neutral-dark">₽ {{ total_price }}</h5>
                </div>
{#                <div class="box-info-cart-inner">#}
{#                  <p class="text-17-medium text-uppercase mb-15">Доставка</p>#}
{#                  <div class="list-radio">#}
{#                    <div class="item-radio">#}
{#                      <label>#}
{#                        <input type="radio" name="shipping" checked="checked">Стандартная: ₽560{{ shipping_cost }}#}
{#                      </label><span class="price-ship">₽{{ shipping_cost }}</span>#}
{#                    </div>#}
{#                    <div class="item-radio">#}
{#                      <label>#}
{#                        <input type="radio" name="shipping">Экспресс: ₽1000#}
{#                      </label>#}
{#                    </div>#}
{#                  </div>#}
{#                  <p class="body-p2 neutral-medium-dark mb-12">Варианты доставки будут уточнены при оформлении.</p>#}
{#                </div>#}
{#                <div class="d-flex align-items-center justify-content-between box-total-bottom">#}
{#                  <h5 class="neutral-medium-dark">Итого</h5>#}
{#                  <h5 class="neutral-dark">₽ {{ total_price }}</h5>#}
{#                </div>#}
                <div class="box-button-cart"><a class="btn btn-black" href="{% url "products:product_checkout" %}">Оформить заказ</a></div>
                <div class="box-other-link"><a class="text-17 link-green" href="#">Бесплатная доставка при заказе от ₽10,000</a><a class="text-17" href="{% url 'products:products_list' %}">Продолжить покупки</a></div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
{% endwith %}
{% endblock %}

templates/products/product_favorite.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% with request.resolver_match.view_name as view_name %}
    <main class="main">
      <section class="section block-banner-cart mb-4" style="padding-top: 120px;">
        <div class="row">
          <div class="col-12">
            <div class="breadcrumbs">
              <ul class="list-inline">
                <li class="list-inline-item nav-link {% if view_name == 'homepage' %}active{% endif %}"> <a href="{% url 'homepage' %}">Главная </a></li>
                <li class="list-inline-item nav-link {% if view_name == 'products:products_list' %}active{% endif %}"> <a href="{% url 'products:products_list' %}">Каталог </a></li>
                <li class="list-inline-item nav-link {% if view_name == 'products:product_cart' %}active{% endif %}"> <a href="{% url 'products:favorite_product' %}">Избранное </a></li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      <section class="section block-cart">
        <div class="row">
          <div class="col-lg-7">
            <div class="box-title-cart">
              <h4>Избранные товары</h4>
              <h6>{% if favorite_items %}{{ favorite_items|length }} товар{{ favorite_items|length|pluralize:"а,ов" }}{% else %}0 товаров{% endif %}</h6>
            </div>
            <div class="list-items-cart">
              {% if favorite_items %}
                {% for item in favorite_items %}
                <div class="item-cart">
                  <div class="item-cart-image">
                    {% if item.product.image %}
                    <img src="{{ item.product.image.url }}" alt="{{ item.product.name }}">
                    {% else %}
                    <img src="{{ item.image.url }}" alt="{{ item.name }}">
                    {% endif %}
                  </div>
                  <div class="item-cart-info">
                    <div class="item-cart-info-1">
                      <a class="text-16-medium" href="#">{{ item.product.name }}</a>
                      <div class="box-info-size-color-product">
                        <p class="box-color"><span class="body-p2 neutral-medium-dark">Цвет:</span><span class="body-p2 neutral-dark">{% if item.color %}{{ item.color }}{% else %}Стандартный{% endif %}</span></p>
                        <p class="box-size"><span class="body-p2 neutral-medium-dark">Размер:</span><span class="body-p2 neutral-dark">{% if item.size %}{{ item.size }}{% else %}Стандартный{% endif %}</span></p>
                      </div>
                    </div>
                    <div class="item-cart-info-2">
                      <p class="body-p2">₽ {{ item.product.price }}</p>
                      <a class="btn-remove-cart" href="{% if request.user.is_authenticated %}{% url 'products:remove_product_to_favorite' item.product.pk %}{% else %}{% url 'products:remove_product_from_cart' item.pk %}{% endif %}"></a>
                    </div>
                  </div>
                </div>
                {% endfor %}
              {% else %}
                <div class="alert alert-info">
                  <p>Ваш список избранного пуст. <a href="{% url 'products:products_list' %}">Перейти в каталог</a></p>
                </div>
              {% endif %}
            </div>
              <div class="coupon-right"><a class="btn btn-border" href="{% url 'products:products_list' %}">Продолжить покупки</a></div>
            </div>
            <div class="box-may-also-like">
              <h4 class="box-border-bottom mb-20">Вам также может понравиться</h4>
              <div class="list-items-also-like">
                {% for product in recommended_products %}
                <div class="item-also-like">
                  <div class="item-also-like-image">
                    {% if product.image %}
                    <img src="{{ product.image.url }}" alt="{{ product.name }}">
                    {% else %}
                    <img src="{% static 'assets/imgs/page/homepage1/product3.png' %}" alt="{{ product.name }}">
                    {% endif %}
                  </div>
                  <div class="item-also-like-info">
                    <div class="item-also-like-info-1">
                      <a class="text-16-medium" href="#">{{ product.name }}</a>
                      <p class="body-2 neutral-medium-dark mb-8">₽ {{ product.price }}</p>
                      <div class="box-color box-size mb-8"><span class="body-p2 neutral-medium-dark">Категория:</span>
                        <div class="dropdown">
                          <button class="btn dropdown-toggle" id="dropdownColor" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <span>{{ product.category.name }}</span>
                          </button>
                        </div>
                      </div>
                    </div>
                    <div class="item-also-like-info-2">
                      <div class="box-form-cart">
                        <div class="form-cart detail-qty"><span class="minus"></span>
                          <input class="qty-val form-control" type="text" name="quantity" value="1" min="1"><span class="plus"></span>
                        </div>
                        <a class="btn btn-black-medium" href="{% url "products:add_product_to_cart" product.pk %}">Добавить в корзину</a>
                        <a class="btn btn-red" href="{% url "products:add_product_to_favorite" product.pk %}">Добавить в избранное</a>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
{% endwith %}
{% endblock %}