MediaMarket/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from products.views import about_us, homepage

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", homepage, name="homepage"),
    path("about-us/", about_us, name="about_us"),
    path("users/", include("users.urls", namespace="users")),
    path("products/", include("products.urls", namespace="products")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from .views import (
    products_list,
    product_detail,
    category_sort,
    category_filter,
    product_cart,
    add_product_to_cart,
    remove_product_from_cart,
    favorite_product,
    add_product_to_favorite,
    remove_product_to_favorite,
    product_checkout,
    users_order,
    order_repeat,
)

app_name = "products"

urlpatterns = [
    path("catalog/", products_list, name="products_list"),
    path("product_detail/<pk>", product_detail, name="product_detail"),
    path("category/sort/", category_sort, name="category_sort"),
    path("category/filter/", category_filter, name="category_filter"),
    path("cart/", product_cart, name="product_cart"),
    path("cart/add/<pk>", add_product_to_cart, name="add_product_to_cart"),
    path("cart/remove/<pk>", remove_product_from_cart, name="remove_product_from_cart"),
    path("favorite/", favorite_product, name="favorite_product"),
    path("favorite/add/<pk>", add_product_to_favorite, name="add_product_to_favorite"),
    path(
        "favorite/remove/<pk>",
        remove_product_to_favorite,
        name="remove_product_to_favorite",
    ),
    path("checkout/", product_checkout, name="product_checkout"),
    path("users_order/", users_order, name="users_order"),
    path("order-repeat/<int:pk>/", order_repeat, name="order_repeat"),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (
    UserLoginView,
    UserRegisterView,
    UserRecoverPasswordView,
    user_profile,
    UserProfileSettingsView,
    user_profile_orders,
)

app_name = "users"

urlpatterns = [
    path("profile/<pk>", user_profile, name="user_profile"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path(
        "recover-password/", UserRecoverPasswordView.as_view(), name="recover-password"
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("settings/", UserProfileSettingsView.as_view(), name="user_profile_settings"),
    path("orders/<pk>", user_profile_orders, name="user_profile_orders"),
]

templates/includes/footer.html
{% load static %}
<footer class="footer footer-white">
      <div class="footer-1">
        <div class="container">
          <div class="row">
            <div class="col-lg-4 mb-30">
              <h6 class="color-white mb-20">About Shop</h6>
              <p class="color-white body-p2 desc-company">Lorem ipsum dolor sit amet, consectetur adipisicing elit.<a href="#">Read more</a></p>
              <p class="neutral-dark body-p2 email-footer">E. hello@uxper.co</p>
              <p class="neutral-dark body-p2 phone-footer">T. (00) 342 489 33</p>
            </div>
            <div class="col-lg-8 mb-30">
              <div class="row">
                <div class="col-lg-3 mb-30">
                  <h6 class="color-white mb-20">Company</h6>
                  <ul class="menu-footer">
                    <li><a href="about-us-1.html">About us</a></li>
                    <li><a href="carrers.html">Careers</a></li>
                    <li><a href="store-location.html">Store Locator</a></li>
                    <li><a href="contact.html">Contact Us</a></li>
                  </ul>
                </div>
                <div class="col-lg-3 mb-30">
                  <h6 class="color-white mb-20">Customer Care</h6>
                  <ul class="menu-footer">
                    <li><a href="about-us-1.html">Size Guide</a></li>
                    <li><a href="custome-service.html">Help &amp; FAQs</a></li>
                    <li><a href="faq.html">Return My Order</a></li>
                    <li><a href="store-location.html">Refer a Friend</a></li>
                  </ul>
                </div>
                <div class="col-lg-3 mb-30">
                  <h6 class="color-white mb-20">Terms &amp; Policies</h6>
                  <ul class="menu-footer">
                    <li><a href="faq.html">Duties &amp; Taxes</a></li>
                    <li><a href="store-location.html">Shipping Info</a></li>
                    <li><a href="store-location.html">Privacy Policy</a></li>
                    <li><a href="store-location.html">Terms Conditions</a></li>
                  </ul>
                </div>
                <div class="col-lg-3 mb-30">
                  <h6 class="color-white mb-20">Follow Us</h6>
                  <ul class="menu-footer">
                    <li><a href="#">Instagram</a></li>
                    <li><a href="#">Facebook</a></li>
                    <li><a href="#">Pinterest</a></li>
                    <li><a href="#">Tiktok</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-2">
        <div class="container">
          <div class="footer-bottom">
            <div class="row align-items-center">
              <div class="col-lg-6 col-md-12 text-center text-lg-start mb-20"><span class="body-p1 color-white">© {{ year }} Guza.Co. All rights reserved</span></div>
              <div class="col-lg-6 col-md-12 text-center text-lg-end mb-20">
                <div class="d-flex justify-content-center justify-content-lg-end align-items-center box-all-payments">
                  <div class="d-inline-block box-payments mr-20"><img src={% static "assets/imgs/template/icons/visa-grey.svg" %} alt=""><img src={% static "assets/imgs/template/icons/master-grey.svg" %} alt=""><img src={% static "assets/imgs/template/icons/stripe-grey.svg" %} alt=""><img src={% static "assets/imgs/template/icons/paypal-grey.svg" %} alt=""></div>
                  <div class="dropdown mr-20">
                    <button class="btn btn-line-bottom dropdown-toggle" id="dropdownLang" type="button" data-bs-toggle="dropdown" aria-expanded="false">EN</button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownLang">
                      <li><a class="dropdown-item" href="#">EN</a></li>
                      <li><a class="dropdown-item" href="#">JP</a></li>
                      <li><a class="dropdown-item" href="#">KR</a></li>
                    </ul>
                  </div>
                  <div class="dropdown">
                    <button class="btn btn-line-bottom dropdown-toggle" id="dropdownCurrency" type="button" data-bs-toggle="dropdown" aria-expanded="false">USD</button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownCurrency">
                      <li><a class="dropdown-item" href="#">USD</a></li>
                      <li><a class="dropdown-item" href="#">EURO</a></li>
                      <li><a class="dropdown-item" href="#">AUD</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>

templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<header class="header sticky-top bg-white shadow-sm">
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light py-3">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url "homepage"%}">
          <img alt="MediaMarket" src="{% static 'assets/imgs/template/mondragon-corporacion.svg' %}" height="40">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0"> 
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'homepage' %}active{% endif %}" aria-current="page" href="{% url "homepage" %}">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'products:products_list' %}active{% endif %}" href="{% url "products:products_list" %}">Каталог</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle {% if view_name == 'products:category_filter' %}active{% endif %}" href="#" id="navbarDropdown" role="button"
                 data-bs-toggle="dropdown" aria-expanded="false">
                Категории
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'products:category_filter' %}?filter=electronic">Электроника</a></li>
                <li><a class="dropdown-item" href="{% url 'products:category_filter' %}?filter=household_goods">Бытовая техника</a></li>
                <li><a class="dropdown-item" href="{% url 'products:category_filter' %}?filter=animal">Животные</a></li>
                <li><a class="dropdown-item" href="{% url 'products:category_filter' %}?filter=podarok">Подарки</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item {% if view_name == 'products:category_filter' %}

                {% endif %} " href="{% url 'products:category_filter' %}">Все категории</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'about_us' %}active{% endif %}" href="{% url "about_us" %}">О нас</a>
            </li>
          </ul>
          <form method="GET" action="{% url "products:products_list" %}" class="d-flex me-3">
            <div class="input-group">
              <input class="form-control" type="text" name="q" value="{{ request.GET.q|default_if_none:'' }}" placeholder="Поиск товаров..." aria-label="Search">
              <button class="btn btn-outline-dark" type="submit">
                <svg width="18" height="18" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path d="M20.031 18.617L24.314 22.899L22.899 24.314L18.617 20.031C17.0237 21.3082 15.042 22.0029 13 22C8.032 22 4 17.968 4 13C4 8.032 8.032 4 13 4C17.968 4 22 8.032 22 13C22.0029 15.042 21.3082 17.0237 20.031 18.617ZM18.025 17.875C19.2941 16.5699 20.0029 14.8204 20 13C20 9.132 16.867 6 13 6C9.132 6 6 9.132 6 13C6 16.867 9.132 20 13 20C14.8204 20.0029 16.5699 19.2941 17.875 18.025L18.025 17.875Z"></path>
                </svg>
              </button>
            </div>
          </form>
          <div class="d-flex align-items-center">
            {% if user.is_authenticated %}
                <a href="{% url 'users:user_profile' user.pk %}" class="btn btn-outline-dark me-3 px-3">{{user.username}} | Профиль</a>
            <form method="post" action="{% url 'users:logout' %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-dark me-3 px-3">Выйти</button>
            </form>
            {% else %}
            <a href="{% url 'users:login' %}" class="btn btn-outline-dark me-3 px-3">Вход</a>
            <a href="{% url 'users:register' %}" class="btn btn-dark me-3 px-3">Регистрация</a>
            {% endif %}
            <a class="position-relative me-3" href="{% url "products:favorite_product" %}" title="Избранное">
              <svg width="24" height="24" viewBox="0 0 28 28" xmlns="http://www.w3.org/2000/svg">
                <path d="M14.001 6.52898C16.35 4.41998 19.98 4.48998 22.243 6.75698C24.505 9.02498 24.583 12.637 22.479 14.993L13.999 23.485L5.52101 14.993C3.41701 12.637 3.49601 9.01898 5.75701 6.75698C8.02201 4.49298 11.645 4.41698 14.001 6.52898ZM20.827 8.16998C19.327 6.66798 16.907 6.60698 15.337 8.01698L14.002 9.21498L12.666 8.01798C11.091 6.60598 8.67601 6.66798 7.17201 8.17198C5.68201 9.66198 5.60701 12.047 6.98001 13.623L14 20.654L21.02 13.624C22.394 12.047 22.319 9.66498 20.827 8.16998Z"></path>
              </svg>
                {% if user.is_authenticated and favorite_count > 0 %}
              <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                {{ favorite_count }}
              </span>
                {% endif %}
            </a>
            <a class="position-relative" href="{% url "products:product_cart" %}" title="Корзина">
              <svg width="24" height="24" viewBox="0 0 28 28" xmlns="http://www.w3.org/2000/svg">
                <path d="M9 10V8C9 6.67392 9.52678 5.40215 10.4645 4.46447C11.4021 3.52678 12.6739 3 14 3C15.3261 3 16.5979 3.52678 17.5355 4.46447C18.4732 5.40215 19 6.67392 19 8V10H22C22.2652 10 22.5196 10.1054 22.7071 10.2929C22.8946 10.4804 23 10.7348 23 11V23C23 23.2652 22.8946 23.5196 22.7071 23.7071C22.5196 23.8946 22.2652 24 22 24H6C5.73478 24 5.48043 23.8946 5.29289 23.7071C5.10536 23.5196 5 23.2652 5 23V11C5 10.7348 5.10536 10.4804 5.29289 10.2929C5.48043 10.1054 5.73478 10 6 10H9ZM9 12H7V22H21V12H19V14H17V12H11V14H9V12ZM11 10H17V8C17 7.20435 16.6839 6.44129 16.1213 5.87868C15.5587 5.31607 14.7956 5 14 5C13.2044 5 12.4413 5.31607 11.8787 5.87868C11.3161 6.44129 11 7.20435 11 8V10Z"></path>
              </svg>
                {% if cart_count > 0 %}
              <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                {{ cart_count }}
              </span>
                {% endif %}
            </a>
          </div>
        </div>
      </div>
    </nav>
  </div>
</header>
{% endwith %}